import {Children,cloneElement,createContext,isValidElement,useContext,useEffect,useState,type ReactNode,type ReactElement} from 'react';
import {vietnamese} from '../data/vietnamese';
type Language='en'|'vi';
const LanguageContext=createContext<{language:Language;setLanguage:(l:Language)=>void}>({language:'en',setLanguage:()=>{}});
export function LanguageProvider({children}:{children:ReactNode}){const [language,setLanguage]=useState<Language>(()=>{try{return localStorage.getItem('fabagain.language')==='vi'?'vi':'en';}catch{return 'en';}});useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem('fabagain.language',language);}catch{/* Reading remains available without storage. */}},[language]);return <LanguageContext.Provider value={{language,setLanguage}}>{children}</LanguageContext.Provider>;}
export function useLanguage(){const {language,setLanguage}=useContext(LanguageContext);
 function t(text:string):string{if(language==='en')return text;const trimmed=text.trim();if(vietnamese[trimmed])return text.replace(trimmed,vietnamese[trimmed]);const dynamic=text.match(/^(Show image |Image note |Source )(\d+): (.+)$/);if(dynamic)return ({'Show image ':'Xem ảnh ','Image note ':'Chú giải ảnh ','Source ':'Nguồn '}[dynamic[1]]??'')+dynamic[2]+': '+t(dynamic[3]);for(const [prefix,translated]of [['Open full-size image: ','Mở ảnh đầy đủ: '],['Open featured exhibit: ','Mở hồ sơ nổi bật: '],['Explore ','Khám phá ']])if(text.startsWith(prefix))return translated+t(text.slice(prefix.length));if(text.endsWith(' · Source in Vietnamese'))return t(text.slice(0,-' · Source in Vietnamese'.length))+' · Nguồn bằng tiếng Việt';let value=text;for(const [en,vi]of [['January','Tháng 1'],['February','Tháng 2'],['March','Tháng 3'],['April','Tháng 4'],['May','Tháng 5'],['June','Tháng 6'],['July','Tháng 7'],['August','Tháng 8'],['September','Tháng 9'],['October','Tháng 10'],['November','Tháng 11'],['December','Tháng 12']])value=value.replace(new RegExp(`\\b${en}\\b`,'g'),vi);for(const [en,vi]of [['Explore ','Khám phá '],['Open featured exhibit: ','Mở hồ sơ nổi bật: '],['Show image ','Xem ảnh '],['Open full-size image: ','Mở ảnh đầy đủ: '],[' image gallery',' — thư viện ảnh'],['Source in Vietnamese','Nguồn bằng tiếng Việt'],['Image source: ','Nguồn ảnh: '],['Research dossier / ','Hồ sơ nghiên cứu / '],['Reviewed ','Rà soát '],[' min read',' phút đọc'],[' sources',' nguồn'],['Supports: ','Làm căn cứ cho: '],['Source review: ','Rà soát nguồn: '],['Source ','Nguồn ']])if(value.includes(en))value=value.replace(en,vi);return value;}
 function localize(node:ReactNode):ReactNode{if(language==='en')return node;if(typeof node==='string')return t(node);if(Array.isArray(node))return Children.map(node,localize);if(!isValidElement(node))return node;const element=node as ReactElement<Record<string,unknown>>;if(element.props.translate==='no')return node;const props:Record<string,unknown>={};for(const key of ['title','aria-label','placeholder','alt'])if(typeof element.props[key]==='string')props[key]=t(element.props[key] as string);if(element.props.children!==undefined)props.children=Children.map(element.props.children as ReactNode,localize);return cloneElement(element,props);}
 return {language,setLanguage,t,localize};
}

