import {assetUrl} from '../lib/assets';
import {newDates} from '../data/newCases';
import {useState} from 'react';
import {ImageCredit} from './ImageCredit';
import {exhibits,sources,type Exhibit} from '../data/exhibits';
import {caseResearch,researchSources,reviewedOn} from '../data/research';
import {exhibitImages} from '../data/images';
import {decisions} from '../data/decisions';
import {downloadNotebook,type Notebook,type NotebookEntry} from '../lib/notebook';
import {useLanguage} from '../lib/language';
const library={...sources,...researchSources};
const eventDates:Record<string,string[]>={...newDates,vsmart:['2018-12-03','2021-05-09','2021-05-17'],moca:['2018-10-16','2024-05-31','2024-07-01','2024-12-04'],wefit:['2020-03-01','2020-05-11','2020-05-12','2020-05-13'],adayroi:['2019-12-17','2019-12-18','2020-01-15']};
const events=exhibits.flatMap(e=>caseResearch[e.id].timeline.map((event,i)=>({...event,exhibit:e,sort:eventDates[e.id][i],key:`${e.id}-${i}`}))).sort((a,b)=>a.sort.localeCompare(b.sort));
export function MuseumTools({open,notebook,update,status}:{open:(e:Exhibit)=>void;notebook:Notebook;update:(id:string,entry:NotebookEntry)=>void;status:string}){
 const {localize,t}=useLanguage();const [tab,setTab]=useState('compare');const [left,setLeft]=useState('vsmart');const [right,setRight]=useState('moca');const [filter,setFilter]=useState('');const [selected,setSelected]=useState(events[0].key);
 const visible=events.filter(e=>!filter||e.exhibit.id===filter);const event=visible.find(e=>e.key===selected)??visible[0];
 const tabs=[['compare','Compare cases'],['timeline','Shared timeline'],['notebook','My collection']];
 return localize(<section id="explore-tools" className="section museum-tools"><div className="section-heading"><div><span className="eyebrow">Explore connections</span><h2>Look across the collection<span className="red-text">.</span></h2><p>Compare decisions, follow events, and keep your own questions.</p></div></div>
 <div className="tools-tabs" role="tablist" aria-label="Exploration tools">{tabs.map(([id,label],i)=><button role="tab" key={id} id={`tool-tab-${id}`} aria-selected={tab===id} aria-controls={`tool-${id}`} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();setTab(tabs[next][0]);document.getElementById(`tool-tab-${tabs[next][0]}`)?.focus();}}>{label}</button>)}</div>
 <div role="tabpanel" id={`tool-${tab}`} aria-labelledby={`tool-tab-${tab}`} tabIndex={0}>
 {tab==='compare'&&<><div className="compare-selectors"><label>First case<select aria-label="First case" value={left} onChange={e=>{const next=e.target.value;if(next===right)setRight(left);setLeft(next);}}>{exhibits.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Second case<select aria-label="Second case" value={right} onChange={e=>{const next=e.target.value;if(next===left)setLeft(right);setRight(next);}}>{exhibits.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label></div><div className="comparison-grid">{[left,right].map(id=>{const e=exhibits.find(e=>e.id===id)!,r=caseResearch[id];return <article key={id} className="comparison-case"><img src={assetUrl(exhibitImages[id].src)} alt={exhibitImages[id].alt}/><ImageCredit image={exhibitImages[id]}/><h3>{e.title}</h3><span className="badge">{e.outcome}</span>{[['Ambition',r.sections[0].paragraphs[0]],['Business model',r.sections[1].paragraphs[0]],['Turning point',r.sections[2].paragraphs[0]],['People & decisions',r.sections[3].paragraphs[0]]].map(([label,p])=>{const item=p as typeof r.sections[0]['paragraphs'][0];return <section key={String(label)}><h4>{String(label)}</h4><p>{item.text}</p><div className="comparison-citations">{item.sources.map(s=><a key={s} href={library[s].url} target="_blank" rel="noreferrer">{library[s].publisher} ↗</a>)}</div></section>})}<section><h4>A lesson to test</h4><p>{r.takeaway}</p><small>Curatorial interpretation</small></section><button className="button outline" onClick={()=>open(e)}>Explore the Story ↗</button></article>})}</div><p className="fine">Comparison reveals differences and questions. It does not establish a shared cause.</p></>}
 {tab==='timeline'&&<><label className="timeline-filter">Filter timeline<select aria-label="Filter timeline" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All exhibits</option>{exhibits.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><div className="shared-timeline"><ol aria-label="Historical events">{visible.map(item=><li key={item.key}><button aria-pressed={event.key===item.key} onClick={()=>setSelected(item.key)}><time>{item.date}</time><strong>{item.exhibit.title}</strong><span>{item.title}</span></button></li>)}</ol><article className="timeline-detail" aria-live="polite"><img src={assetUrl(exhibitImages[event.exhibit.id].src)} alt={exhibitImages[event.exhibit.id].alt}/><ImageCredit image={exhibitImages[event.exhibit.id]}/><p className="fine">Exhibit image · Historical context, not a photograph of this event</p><span className="eyebrow">{event.date}</span><h3>{event.title}</h3><p>{event.text}</p><a className="text-link" href={library[event.source].url} target="_blank" rel="noreferrer">{library[event.source].publisher} ↗</a><button className="button outline" onClick={()=>open(event.exhibit)}>Explore the Story ↗</button></article></div></>}
 {tab==='notebook'&&<><p>Saved exhibits and notes are stored only in this browser. Export a copy to keep them when changing devices or clearing browser data.</p><p role="status" className="fine">{status}</p><button className="button outline" onClick={()=>downloadNotebook(notebook)}>Export my notebook ↗</button><div className="saved-grid">{exhibits.filter(e=>notebook[e.id]?.saved||notebook[e.id]?.note).map(e=><article className="saved-case" key={e.id}><h3>{e.title}</h3><p className="private-note" translate="no">{notebook[e.id].note||t('No note yet.')}</p><div className="saved-actions"><button onClick={()=>open(e)}>Open exhibit & notes ↗</button><button onClick={()=>update(e.id,{saved:false,note:''})}>Remove exhibit and note</button></div></article>)}</div>{!exhibits.some(e=>notebook[e.id]?.saved||notebook[e.id]?.note)&&<div className="empty"><h3>Your collection starts with a question.</h3><p>Open an exhibit to save it or write a private note.</p><a className="text-link" href="#collection">Browse exhibits ↗</a></div>}</>}
 </div></section>);
}
export function ExhibitActions({id,entry,update,status}:{id:string;entry:NotebookEntry;update:(id:string,e:NotebookEntry)=>void;status:string}){
 const {localize}=useLanguage();const [copied,setCopied]=useState('');const link=new URL(`#exhibit=${id}`,window.location.href).href;
 async function copy(){try{await navigator.clipboard.writeText(link);setCopied('Link copied.');}catch{setCopied('Copy the link from the field below.');}}
 return localize(<div className="exhibit-actions"><div className="saved-actions"><button className="button outline" aria-pressed={entry.saved} onClick={()=>update(id,{...entry,saved:!entry.saved})}>{entry.saved?'Saved to my collection ✓':'Save to my collection +'}</button><button className="button outline" onClick={copy}>Copy exhibit link ↗</button></div>{copied&&<div className="share-result"><p role="status">{copied}</p><label>Exhibit link<input readOnly value={link} onFocus={e=>e.target.select()}/></label></div>}<details><summary>My private note</summary><label className="note-label">What would you carry into the next attempt?<textarea maxLength={10000} rows={4} value={entry.note} onChange={e=>update(id,{...entry,note:e.target.value})} placeholder="Write a question, observation, or lesson…"/></label><p className="fine" role="status">{status||'Notes stay in this browser and are saved as you type.'}</p><div className="saved-actions"><button onClick={()=>downloadNotebook({[id]:entry})}>Export this note ↗</button><button onClick={()=>update(id,{...entry,note:''})}>Clear note</button></div></details></div>);
}
export function DecisionMoment({id}:{id:string}){const {localize}=useLanguage();const data=decisions[id];const [choice,setChoice]=useState<number|null>(null);const [reveal,setReveal]=useState(false);return localize(<section className="decision-moment"><span className="eyebrow">Pause & consider</span><h3>What would you do?</h3><p className="fine">{data.moment}</p><p className="lead">{data.question}</p><p className="fine">A hypothetical exercise based on this case. There is no scored or proven best answer.</p><div className="decision-options" role="group" aria-label="Consider a decision">{data.choices.map((c,i)=><button key={i} aria-pressed={choice===i} onClick={()=>{setChoice(i);setReveal(false);}}><span>0{i+1}</span>{c.title}</button>)}</div>{choice!==null&&<div className="decision-response" aria-live="polite"><h4>A trade-off to consider</h4><p>{data.choices[choice].tradeoff}</p><button className="button outline" onClick={()=>setReveal(true)}>Reveal the documented outcome ↓</button></div>}{reveal&&<div className="decision-reveal" aria-live="polite"><h4>What the record shows</h4><p>{data.reveal}</p><a className="text-link" href={library[data.source].url} target="_blank" rel="noreferrer">{library[data.source].publisher} ↗</a></div>}</section>);}
export function ResearchTrail({id}:{id:string}){const {localize}=useLanguage();const r=caseResearch[id];return localize(<section className="story-section research-trail"><h3 id="case-trail" tabIndex={-1}>Follow the research trail</h3><p>Follow a claim back to its source, then consider what that source can establish.</p>{[...r.sections.flatMap(s=>s.paragraphs),...r.evidence].filter(p=>p.sources.length).map((p,i)=><details key={i}><summary>{p.text}</summary><p className="evidence-label">{p.label||'Source-backed account'}</p>{p.sources.map(id=><div className="trail-source" key={id}><a href={library[id].url} target="_blank" rel="noreferrer">{library[id].title} ↗</a><p className="fine">{library[id].kind} · {library[id].publisher} · {library[id].date}</p><p>{library[id].claims}</p></div>)}</details>)}<h4>Editorial history</h4><ol><li><time>September 28, 2026</time><p>Two new dossiers added: BAEMIN Vietnam and Air Mekong, with source images, bilingual research and learning activities.</p></li><li><time>September 28, 2026</time><p>Research dossier and visual archive expanded; comparison, learning activities, bilingual reading and claim-to-source navigation added.</p></li></ol><p className="fine">Source review: {reviewedOn}. Editorial-history dates record museum revisions, not the dates of the original events.</p><p className="fine">Found an error? Use “Suggest a Story” to prepare a correction with the claim and supporting source. Proposals stay on your device until you export and share them yourself.</p></section>);}
