import {useLanguage} from '../lib/language';
import {useEffect,useState,type FormEvent} from 'react';
import {blankProposal,loadDraft,saveDraft,deleteDraft,exportDraft,validateProposal,type Proposal} from '../lib/storage';
export function ProposalForm(){const {localize}=useLanguage();const [draft,setDraft]=useState<Proposal>(blankProposal);const [message,setMessage]=useState('');const [errors,setErrors]=useState<Partial<Record<keyof Proposal,string>>>({});
 useEffect(()=>{const loaded=loadDraft();if(loaded.draft){setDraft(loaded.draft);setMessage('Your saved draft has been restored. It has not been sent.');}else if(loaded.error)setMessage(loaded.error);},[]);
 function action(event:FormEvent,mode:'save'|'export'){event.preventDefault();const next=validateProposal(draft);setErrors(next);if(Object.keys(next).length){setMessage('Please check the highlighted fields.');requestAnimationFrame(()=>document.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());return;}if(mode==='save')setMessage(saveDraft(draft));else{exportDraft(draft);setMessage('JSON export prepared. Your proposal has not been sent.');}}
 const field=(key:keyof Proposal,label:string,multiline=false)=><label className={multiline?'full':''}>{label}{key==='contributor'?' (optional)':' *'}{multiline?<textarea id={key} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined} rows={3}/>:<input id={key} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} type={key==='url'?'url':'text'} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>}{errors[key]&&<span className="error" id={`${key}-error`}>{errors[key]}</span>}</label>;
 return localize(<form noValidate onSubmit={e=>action(e,'save')}><div className="form-grid">{field('name','Proposed exhibit name')}<label>Category *<select id="category" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} aria-invalid={!!errors.category} aria-describedby={errors.category?'category-error':undefined}><option value="">Choose a category</option>{['Consumer Technology','Fintech','Commerce','Services','Other'].map(c=><option key={c} value={c}>{c}</option>)}</select>{errors.category&&<span id="category-error" className="error">{errors.category}</span>}</label>{field('happened','What happened?',true)}{field('reason','Why does this story belong in the collection?',true)}{field('url','Supporting source URL')}{field('contributor','Contributor name')}</div><div className="form-actions"><button className="button red" type="submit">Save Draft <span>↓</span></button><button className="button outline" type="button" onClick={e=>action(e,'export')}>Export JSON ↗</button><button className="text-button" type="button" onClick={()=>{if(deleteDraft()){setDraft({...blankProposal});setErrors({});setMessage('Draft deleted from this device.');}else setMessage('The saved draft could not be deleted because device storage is unavailable.');}}>Delete draft</button></div><p className="form-status" role="status">{message}</p></form>);
}
