import {useEffect,useRef} from 'react';
import {sources,curatorialNotes,type Exhibit} from '../data/exhibits';
import {ExhibitGallery} from './ExhibitGallery';
import {caseResearch,researchSources,reviewedOn,type ResearchParagraph} from '../data/research';
const sourceLibrary={...sources,...researchSources};
export function StoryPanel({exhibit,onClose}:{exhibit:Exhibit|null;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!exhibit)return;const dialog=ref.current!;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow=overflow;previous?.focus();};},[exhibit]);
 if(!exhibit)return null;
 const e=exhibit,r=caseResearch[e.id],note=curatorialNotes[e.id];
 const readingMinutes=Math.max(1,Math.ceil((JSON.stringify(r.sections)+JSON.stringify(r.evidence)+JSON.stringify(note)).split(/\s+/).length/200));
 const citation=(id:string)=><a key={id} className="citation" href={sourceLibrary[id].url} target="_blank" rel="noreferrer" title={`${sourceLibrary[id].title}${sourceLibrary[id].language==='Vietnamese'?' · Source in Vietnamese':''}`} aria-label={`Source ${r.sourceIds.indexOf(id)+1}: ${sourceLibrary[id].title}${sourceLibrary[id].language==='Vietnamese'?' · Source in Vietnamese':''}`}>[{r.sourceIds.indexOf(id)+1}]</a>;
 const paragraph=(p:ResearchParagraph,i:number)=><div className="research-paragraph" key={i}>{p.label&&<span className="evidence-label">{p.label}</span>}<p>{p.text} {p.sources.map(citation)}</p></div>;
 function jump(id:string){const target=ref.current?.querySelector<HTMLElement>(`#${id}`);target?.scrollIntoView({block:'start'});target?.focus({preventScroll:true});}
 return <dialog ref={ref} className="story-panel" aria-labelledby="story-title" onCancel={onClose} onClick={event=>{if(event.target===ref.current)onClose();}} onKeyDown={event=>{if(event.key!=='Tab')return;const items=ref.current!.querySelectorAll<HTMLElement>('button,a[href],[tabindex="0"]');const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}>
 <div className="panel-top"><span className="eyebrow">Research dossier / {e.accession}</span><button autoFocus onClick={onClose} aria-label="Close exhibit story">Close ×</button></div>
 <div className="panel-content"><span className="eyebrow">{e.category} · {e.eventYear}</span><h2 id="story-title">{e.title}</h2><span className="badge">{e.outcome}</span><p className="lead dossier-subtitle">{r.subtitle}</p><div className="research-meta"><span>{readingMinutes} min read</span><span>{r.sourceIds.length} sources</span><span>Reviewed {reviewedOn}</span></div>
 <ExhibitGallery key={e.id} id={e.id} title={e.title}/>
 <aside className="research-scope"><strong>Scope of this case</strong><p>{r.scope}</p><p>Desk research from public documents and reporting. No interviews, internal records or independent audit were conducted.</p></aside>
 <div className="story-toc" role="navigation" aria-label="Case study sections">{[['ambition','Ambition'],['model','Business model'],['timeline','Timeline'],['impact','People & decisions'],['evidence','Evidence'],['reflection','Reflection'],['sources','Sources']].map(([id,label])=><button key={id} onClick={()=>jump(`case-${id}`)}>{label}</button>)}</div>
 {r.sections.map((section,i)=><section className="story-section" key={section.title}><span className="eyebrow">{i<3?`0${i+1}`:'03 / Continued'}</span><h3 id={`case-${['ambition','model','timeline','impact'][i]}`} tabIndex={-1}>{section.title}</h3>{section.paragraphs.map(paragraph)}{i===2&&<ol className="case-timeline">{r.timeline.map(event=><li key={event.date}><time>{event.date}</time><h4>{event.title}</h4><p>{event.text} {citation(event.source)}</p></li>)}</ol>}</section>)}
 <section className="story-section"><span className="eyebrow">04</span><h3 id="case-evidence" tabIndex={-1}>What the Evidence Says</h3>{r.evidence.map(paragraph)}<div className="unknowns"><h4>What remains unverified</h4><ul>{r.unknowns.map(q=><li key={q}>{q}</li>)}</ul><p>These are limits of the reviewed record, not claims that no other evidence exists.</p></div></section>
 <section className="reflection"><span className="eyebrow">05 / The FabAgain Reflection</span><h3 id="case-reflection" tabIndex={-1}>{e.reflection}</h3><p className="interpretation-label">Curatorial interpretation · Not a proven explanation of this outcome</p><p>{r.takeaway}</p><p>{note.lens}</p><h4>A possible test for the next attempt</h4><p>{note.experiment}</p><h4>A question to leave with</h4><p>{note.question}</p></section>
 <section className="story-section"><span className="eyebrow">06</span><h3 id="case-sources" tabIndex={-1}>Sources & Research Notes</h3><p className="fine source-method">Company statements establish what was announced. Reporting adds context and attributed accounts. A source repeating an announcement is not a separate verification of its outcome. Translations and paraphrases are FabAgain’s; publication dates follow the publishers.</p>{r.sourceIds.map((id,i)=>{const s=sourceLibrary[id];return <div className="source" key={id}><span className="evidence-label">[{i+1}] {s.kind}</span><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><p>{s.publisher} · {s.date}{s.language==='Vietnamese'?<><br/>Source in Vietnamese</>:null}</p><p>Supports: {s.claims}</p></div>;})}<p className="fine">These are dated historical cases, not current-status assessments. Additional evidence may change the interpretation. Corrections should identify the claim and the supporting document.</p></section><button className="button outline" onClick={onClose}>Return to the Collection ↗</button>
 </div></dialog>;
}
