import {useEffect,useRef} from 'react';
import {sources,curatorialNotes,type Exhibit} from '../data/exhibits';
export function StoryPanel({exhibit,onClose}:{exhibit:Exhibit|null;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!exhibit)return;const dialog=ref.current!;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow=overflow;previous?.focus();};},[exhibit]);
 if(!exhibit)return null;const e=exhibit;
 return <dialog ref={ref} className="story-panel" aria-labelledby="story-title" onCancel={onClose} onClick={event=>{if(event.target===ref.current)onClose();}} onKeyDown={event=>{if(event.key!=='Tab')return;const items=ref.current!.querySelectorAll<HTMLElement>('button,a[href],[tabindex="0"]');const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}>
 <div className="panel-top"><span className="eyebrow">Collection / {e.accession}</span><button autoFocus onClick={onClose} aria-label="Close exhibit story">Close ×</button></div>
 <div className="panel-content"><span className="eyebrow">{e.category} · {e.eventYear}</span><h2 id="story-title">{e.title}</h2><span className="badge">{e.outcome}</span><p className="lead">{e.summary}</p><div className="dates">{e.dates.map(d=><p key={d.label}><strong>{d.label}</strong><br/>{d.date}</p>)}</div>
 {([['The Ambition',e.story.ambition],['The Idea',e.story.idea],['What Happened',e.story.happened],['What the Evidence Says',e.story.evidence]] as const).map(([title,body],i)=><section className="story-section" key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{body}</p></section>)}
 <section className="reflection"><span className="eyebrow">05 / The FabAgain Reflection</span><h3>{e.reflection}</h3><p className="interpretation-label">Curatorial interpretation · Not a proven explanation of this outcome</p><p>{curatorialNotes[e.id].lens}</p><h4>A possible test for the next attempt</h4><p>{curatorialNotes[e.id].experiment}</p><h4>A question to leave with</h4><p>{curatorialNotes[e.id].question}</p></section>
 <section className="story-section"><span className="eyebrow">06</span><h3>Sources</h3>{e.sourceIds.map(id=>{const s=sources[id];return <div className="source" key={id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><p>{s.publisher} · {s.date}<br/>{s.kind}{s.language==='Vietnamese'?' · Source in Vietnamese':''}</p><p>Supports: {s.claims}</p></div>;})}<p className="fine">These sources describe dated events, not each organization’s current status.</p></section></div></dialog>;
}
