import {assetUrl} from './lib/assets';
import {newLessons} from './data/newCases';
import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {exhibits,type Exhibit} from './data/exhibits';
import {filterExhibits,randomExhibit,normalize} from './lib/search';
import {StoryPanel} from './components/StoryPanel';
import {ProposalForm} from './components/ProposalForm';
import {exhibitImages} from './data/images';
import {ImageCredit} from './components/ImageCredit';
import {MuseumTools} from './components/MuseumTools';
import {useLanguage} from './lib/language';
import {notebookKey,parseNotebook,type Notebook,type NotebookEntry} from './lib/notebook';
const lessons=[...newLessons,['Capabilities outlive products.','What knowledge could find a second use when a product line ends?','vsmart'],['An ending is a user experience.','How can a transition account for balances, support and trust?','moca'],['Promises deserve stress tests.','What happens to customer commitments when a service cannot continue?','wefit'],['A new direction needs evidence.','How do we distinguish a proposed redesign from a completed transition?','adayroi']];
export default function App(){const {language,setLanguage,localize,t}=useLanguage();const [notebook,setNotebook]=useState<Notebook>({});const [notebookStatus,setNotebookStatus]=useState('');
 useEffect(()=>{try{setNotebook(parseNotebook(localStorage.getItem(notebookKey)));}catch{setNotebookStatus('Saved notes could not be read. You can still write and export new notes.');}},[]);
 function updateNotebook(id:string,entry:NotebookEntry){const next={...notebook,[id]:entry};setNotebook(next);try{localStorage.setItem(notebookKey,JSON.stringify(next));setNotebookStatus('Saved on this device.');}catch{setNotebookStatus('Device storage is unavailable. Export your notebook to keep this session’s notes.');}}
 function openExhibit(e:Exhibit|null){if(!e)return;window.location.hash='exhibit='+e.id;setActive(e);}
 function closeExhibit(){history.replaceState(null,'',window.location.pathname+window.location.search+'#collection');setActive(null);}
 useEffect(()=>{function route(){const id=window.location.hash.match(/^#exhibit=([a-z0-9-]+)$/)?.[1];setActive(exhibits.find(e=>e.id===id)??null);}route();window.addEventListener('hashchange',route);window.addEventListener('popstate',route);return()=>{window.removeEventListener('hashchange',route);window.removeEventListener('popstate',route);};},[]);
const [menu,setMenu]=useState(false);const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [outcome,setOutcome]=useState('');const [active,setActive]=useState<Exhibit|null>(null);const results=filterExhibits(exhibits,'',category,outcome).filter(e=>normalize(`${e.title} ${e.organization} ${e.summary} ${t(e.title)} ${t(e.summary)} ${t(e.category)} ${t(e.outcome)}`).includes(normalize(query)));const reset=()=>{setQuery('');setCategory('');setOutcome('');};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_exhibits',description:'Set the visible museum search and filters; returns matching exhibit names.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string'},outcome:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object')throw Error('Expected a filter object.');const v=input as Record<string,unknown>;if(Object.keys(v).some(k=>!['query','category','outcome'].includes(k))||Object.values(v).some(x=>typeof x!=='string'))throw Error('Filters must be strings.');const q=String(v.query??''),c=String(v.category??''),o=String(v.outcome??'');if(c&&!exhibits.some(e=>e.category===c)||o&&!exhibits.some(e=>e.outcome===o))throw Error('Unknown category or outcome.');flushSync(()=>{setQuery(q);setCategory(c);setOutcome(o);});return filterExhibits(exhibits,q,c,o).map(e=>({id:e.id,title:e.title}));}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability. */}return()=>lifecycle.abort();},[]);
 return localize(<><a className="skip" href="#collection">Skip to exhibits</a><header><a className="brand" href="#top" aria-label="FabAgain home">Fab<span>Again</span><i aria-hidden="true">↗</i><small>by FABCOM</small></a><button className="menu-toggle" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?'Close ×':'Menu +'}</button><div className="language-switch" role="group" aria-label="Language"><button lang="en" aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>EN</button><button lang="vi" aria-pressed={language==='vi'} onClick={()=>setLanguage('vi')}>VI</button></div><nav id="navigation" className={menu?'open':''} aria-label="Main navigation" onKeyDown={e=>{if(e.key==='Escape'){setMenu(false);document.querySelector<HTMLElement>('.menu-toggle')?.focus();}}}><a onClick={()=>setMenu(false)} href="#collection">Exhibits</a><a onClick={()=>setMenu(false)} href="#explore-tools">Explore tools</a><a onClick={()=>setMenu(false)} href="#lessons">Lessons</a><a onClick={()=>setMenu(false)} href="#about">About FABCOM</a><a onClick={()=>setMenu(false)} className="nav-action" href="#suggest">Suggest a Story ↗</a></nav></header>
 <main id="top"><section className="hero"><div className="hero-label eyebrow"><span className="red-dot"/>Vietnam’s Digital Museum of Failure & Innovation</div><div className="hero-grid"><div className="hero-copy"><h1>Big ideas.<br/>Unexpected<br/>endings.<br/><em>Lessons worth<br/>keeping.</em></h1><p>Explore Vietnamese products, services, and experiments that took an unexpected turn. FabAgain looks beyond the outcome to understand the ambition, the decisions, and the questions worth carrying forward.</p><div className="hero-actions"><a className="button red" href="#collection">Explore the Exhibits <span>↘</span></a><a className="text-link" href="#lessons">Why These Stories Matter ↗</a></div><p className="creator">Created and curated by <strong>FABCOM, Vietnam.</strong></p></div><figure className="hero-art"><div className="art-label eyebrow">From the source archive <span>Collection 01—{String(exhibits.length).padStart(2,'0')}</span></div><div className="archive-grid">{exhibits.map(e=><button key={e.id} onClick={()=>openExhibit(e)} aria-label={`Open featured exhibit: ${e.title}`}><img src={assetUrl(exhibitImages[e.id].src)} alt={exhibitImages[e.id].alt}/><span>{e.accession} / {e.title} ↗</span></button>)}</div><figcaption><span>Real products. Documented stories.</span><small>Source-published images · Credits in each exhibit</small></figcaption><div className="margin-note"><span aria-hidden="true">↳</span> Not every discontinued product<br/>is a failed idea.</div></figure></div><div className="hero-bottom"><span>Every attempt leaves a lesson.</span><span className="eyebrow">An open invitation to look again <span aria-hidden="true">↓</span></span></div></section>
 <section id="collection" className="collection section"><div className="section-heading"><div><span className="eyebrow">01 / The exhibits</span><h2>The Collection<span className="red-text">.</span></h2><p>Different ambitions. Different outcomes. Stories worth examining.</p></div><button className="button outline" disabled={!results.length} onClick={()=>openExhibit(randomExhibit(results)??null)}>Surprise Me <span>↗</span></button></div><div className="filters"><label className="search-label"><span className="sr-only">Search exhibits</span><span aria-hidden="true">⌕</span><input placeholder="Search a story, company, or idea…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="sr-only">Filter by category</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(exhibits.map(e=>e.category))].map(c=><option key={c} value={c}>{c}</option>)}</select></label><label><span className="sr-only">Filter by outcome</span><select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">All outcomes</option>{[...new Set(exhibits.map(e=>e.outcome))].map(o=><option key={o} value={o}>{o}</option>)}</select></label></div><div className="result-line"><span role="status">{results.length} of {exhibits.length} exhibits</span><button className="text-button" onClick={reset}>Reset filters ↺</button></div><div className="exhibit-grid">{results.map(e=><article className="exhibit" key={e.id}><button className={`exhibit-visual authentic ${e.id}`} onClick={()=>openExhibit(e)} aria-label={`Explore ${e.title}`}><img src={assetUrl(exhibitImages[e.id].src)} alt={exhibitImages[e.id].alt} loading="lazy"/><span className="accession">{e.accession}</span><span className="event-year">{e.eventYear}</span><span className="visual-caption">{exhibitImages[e.id].kind}</span><span className="open-icon" aria-hidden="true">↗</span></button><ImageCredit image={exhibitImages[e.id]}/><div className="card-meta"><span className="eyebrow">{e.category}</span><span className="badge">{e.outcome}</span></div><h3>{e.title}</h3><p>{e.summary}</p><button className="story-link" onClick={()=>openExhibit(e)}>Explore the Story <span>↗</span></button></article>)}</div>{!results.length&&<div className="empty"><h3>No stories match just yet.</h3><p>Try a broader search or clear a filter to explore the collection.</p><button className="button outline" onClick={reset}>Reset filters</button></div>}<p className="collection-note">A small curated starting collection, not an assessment of Vietnamese innovation as a whole. Images come from the linked company, reporting and project sources. Original Vietnamese text is preserved inside historical images; captions and exhibit text are available in English and Vietnamese.</p></section>
 <MuseumTools open={openExhibit} notebook={notebook} update={updateNotebook} status={notebookStatus}/><section id="lessons" className="lessons section"><span className="eyebrow">02 / Questions to carry forward</span><div className="lesson-heading"><h2>What Can the<br/>Next Attempt Learn?</h2><p>Outcomes are a starting point for inquiry.<br/>These are curatorial reflections, not formulas for success.</p></div><div className="lesson-grid">{lessons.map(([title,description,id],i)=><article key={id}><span className="lesson-number">0{i+1}</span><h3>{title}</h3><p>{description}</p><button onClick={()=>openExhibit(exhibits.find(e=>e.id===id)!)}>Reflect with {exhibits.find(e=>e.id===id)!.title} ↗</button></article>)}</div></section>
 <section id="about" className="about section"><div><span className="eyebrow">03 / Behind the collection</span><h2>An Initiative<br/>by <span className="red-text">FABCOM</span></h2><p className="about-principle">“We examine decisions and outcomes, not the worth of the people behind them.”</p></div><div><p className="lead">FabAgain is a digital museum created and curated by FABCOM, an organization based in Vietnam. Through documented stories of products, services, and experiments, the platform invites visitors to examine setbacks with curiosity rather than judgment.</p><h3>Our editorial approach</h3><ul className="principles">{['Vietnam-related innovation stories.','Documented events rather than rumors.','Clear distinctions between different outcomes.','Sources attached to factual claims.','Curatorial interpretations identified as interpretations.','Corrections supported by evidence.'].map((p,i)=><li key={p}><span>0{i+1}</span>{p}</li>)}</ul><p className="fine">Have evidence that adds context or corrects a story? Prepare a proposal below, identifying the exhibit and the source. This version saves it locally for you to keep.</p></div></section>
 <section id="suggest" className="suggest section"><div><span className="eyebrow">04 / Keep the collection curious</span><h2>What Story<br/>Should We<br/>Explore Next?</h2><p>The next useful question could begin with a story you know.</p><div className="local-note"><span className="eyebrow">A note before you begin</span><p>Prepare a proposal and save it on this device. Proposals are not sent to FABCOM from this version of the website.</p><p className="fine">Required fields are marked *. Contributions are not automatically published.</p></div></div><ProposalForm/></section></main>
 <footer><div className="footer-top"><a className="brand" href="#top">Fab<span>Again</span><i aria-hidden="true">↗</i></a><p>Every attempt leaves a lesson.</p><a href="#top">Back to top ↑</a></div><div className="footer-bottom"><p>Created and curated by FABCOM, Vietnam.<br/><span className="fine">A digital exhibition. Historical events, carefully distinguished.</span></p><div><a href="#collection">Exhibits</a><a href="#lessons">Lessons</a><a href="#about">About FABCOM</a></div><p className="fine">Conceptual inspiration: <a href="https://museumoffailure.com/" target="_blank" rel="noreferrer">Museum of Failure ↗</a><br/>An independent FABCOM initiative. No partnership or endorsement implied.</p></div><div className="footer-contact"><address><span className="eyebrow">Website correspondence</span><strong translate="no">Le Gia Thang</strong><div className="footer-contact-links"><a href="mailto:thangl2411@gmail.com" translate="no">thangl2411@gmail.com</a><a href="tel:+84839703942" translate="no">+84 839 703 942</a></div></address><p className="footer-copyright"><span translate="no">© 2026 FabCom.</span> <span>All rights reserved.</span></p></div></footer><StoryPanel exhibit={active} onClose={closeExhibit} entry={notebook[active?.id??'']??{saved:false,note:''}} update={updateNotebook} status={notebookStatus}/></>);
}

